sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7-dev'
before_script:
- if [ $TRAVIS_PYTHON_VERSION = 2.7 ]; then pip install 'commonconf<1.0' ; fi
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install coveralls
script:
- pycodestyle ems_client
- coverage run --source=ems_client/ ems_client/test.py -v
after_script:
- coveralls
before_deploy:
- find ems_client/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > ems_client/VERSION
deploy:
  provider: pypi
  user: bradleyb
  skip_cleanup: true
  password:
    secure: "PQfbdR7BlyY/njs5kRph4/k/Fad1BFAshVhv7s6XT10n6wTe49SONrd7TJys8YgwD0W/nGziNOkhuJHHOUbUWQoW9e8YU+JF2dgpIN9lU1K3Goh6UA9wbnhVWxlMqsyaFfGQGkwq0qTAGTsHke7rLZEm6YQf/XG/snQwViqnOsZTSwieSPG7Dadv/Uv8FQCRnbVPz0AtfFcDV3y/pvqisZWS01i5hWgWL7ua/AG1TULt6butqCjwXpQ0uwVC2ZvnvwBeXTo2c4cxy+qYBpAS9z0ZPdfHPKlz4UVkiIB4S6O83JkZrUtTSAx/kZenfPO1/UtzwjoJHAlZAqjmHZtWuArOGoVDWxaTPMCj2U43J/INQGGkrG05Zon6Zplpbmx7lgElrZw1yaUp2HMYLdtRoo7Nu8eQh5tRAwPpNPIxlbMhSMq4DpmMA481WILh8v0cCudgvIVaSvIsCq/w9ML2/p2BzpKSGRLmVpqchLt4NP7noqVZmdw23F18u66MZZ/lyhLFU666s0SoQ/MhQSgvOY+BgbYEvdgomKgLheOCOG7CaitO4TpNapRk3lb1QWYad31Ts2c3q8WPr3XdtHvnjfoh3gfyveq4JTlFJG4Co5gZUtRCYmKrsytBsEy45ylyqMAU17u+dv8ohY/1UpX+5XmBsvV+74QMzbsbvJDu33c="
  on:
    tags: true
    python: '2.7'
